apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubehunterreports.khulnasoft.github.io
  labels:
    app.kubernetes.io/managed-by: starboard
spec:
  group: khulnasoft.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    singular: kubehunterreport
    plural: kubehunterreports
    kind: KubeHunterReport
    listKind: KubeHunterReportList
    categories:
      - all
    shortNames:
      - kubehunter
