env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: starboard
    main: ./cmd/starboard/main.go
    binary: starboard
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
dockers:
  - image_templates:
      - "docker.io/khulnasoft/starboard:{{ .Version }}"
    binaries:
      - starboard
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.description=Kubernetes-native security toolkit"
      - "--label=org.label-schema.vendor=Khulnasoft Security"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.build-date={{ .Date }}"
      - "--label=org.label-schema.vcs=https://github.com/khulnasoft/starboard"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
